/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;
import model.entities.Aeroporto;
import model.entities.Voo;
import model.entities.chegadaComparator;
import model.entities.saidaComparator;

/**
 *
 * @author Administrador
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private ArrayList<Aeroporto> listaAero;
    private ArrayList<Voo> listaVoo;
    
    
    
    public TelaPrincipal(){
        
    }
    
    public TelaPrincipal(ArrayList<Aeroporto> listaAero, ArrayList<Voo> listaVoo) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);                
        
        this.listaAero = listaAero;
        this.listaVoo = listaVoo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaChegadas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaSaidas = new javax.swing.JTable();
        textData = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta Voos");

        textCod.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Código do Aeroporto");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Data");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabelaChegadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hora", "Origem", "Cia.", "Voo", "Portão", "Estimado", "Situação"
            }
        ));
        tabelaChegadas.setFocusable(false);
        tabelaChegadas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaChegadas.setRowHeight(25);
        tabelaChegadas.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tabelaChegadas.setShowVerticalLines(false);
        tabelaChegadas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaChegadas);
        if (tabelaChegadas.getColumnModel().getColumnCount() > 0) {
            tabelaChegadas.getColumnModel().getColumn(0).setPreferredWidth(20);
            tabelaChegadas.getColumnModel().getColumn(2).setPreferredWidth(10);
            tabelaChegadas.getColumnModel().getColumn(3).setPreferredWidth(20);
            tabelaChegadas.getColumnModel().getColumn(4).setPreferredWidth(10);
            tabelaChegadas.getColumnModel().getColumn(5).setPreferredWidth(30);
            tabelaChegadas.getColumnModel().getColumn(6).setPreferredWidth(30);
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Chegadas");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Saídas");

        tabelaSaidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hora", "Destino", "Cia.", "Voo", "Portão", "Estimado", "Situação"
            }
        ));
        tabelaSaidas.setFocusable(false);
        tabelaSaidas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelaSaidas.setRowHeight(25);
        tabelaSaidas.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tabelaSaidas.setShowVerticalLines(false);
        tabelaSaidas.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabelaSaidas);
        if (tabelaSaidas.getColumnModel().getColumnCount() > 0) {
            tabelaSaidas.getColumnModel().getColumn(0).setPreferredWidth(20);
            tabelaSaidas.getColumnModel().getColumn(2).setPreferredWidth(10);
            tabelaSaidas.getColumnModel().getColumn(3).setPreferredWidth(20);
            tabelaSaidas.getColumnModel().getColumn(4).setPreferredWidth(10);
            tabelaSaidas.getColumnModel().getColumn(5).setPreferredWidth(30);
            tabelaSaidas.getColumnModel().getColumn(6).setPreferredWidth(30);
        }

        try {
            textData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textData.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textCod, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textData, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textData, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, textCod});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, jLabel5});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        atualizarTabelaSaidas();
        atualizarTabelaChegadas();        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    public void atualizarTabelaChegadas(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Chegada Prevista");
        modelo.addColumn("Origem");
        modelo.addColumn("Cia.");
        modelo.addColumn("Voo");
        modelo.addColumn("Portao");
        modelo.addColumn("Chegada Estimada");
        modelo.addColumn("Situacao");
        // chegadaPrev - origem - cia. - voo - portao - chegadaEstimado - situacao        
        
        Collections.sort(this.listaVoo, new chegadaComparator());
        
        for(Voo obj : this.listaVoo){
            if(obj.consultarChegadas(textData.getText(), textCod.getText()) != null){                
                String[] result = obj.consultarChegadas(textData.getText(), textCod.getText());            
                modelo.addRow(result);                                
            }
        }
        tabelaChegadas.setModel(modelo);  
                
        tabelaChegadas.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tabelaChegadas.getTableHeader().setOpaque(false);
        tabelaChegadas.getTableHeader().setBackground(Color.WHITE);
        tabelaChegadas.getTableHeader().setForeground(Color.GRAY);
        tabelaChegadas.setRowHeight(25);
    }
    
    public void atualizarTabelaSaidas(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Saída Prevista");
        modelo.addColumn("Destino");
        modelo.addColumn("Cia.");
        modelo.addColumn("Voo");
        modelo.addColumn("Portao");
        modelo.addColumn("Saída Estimada");
        modelo.addColumn("Situacao");
        
        //chegadaComparator comparador = new chegadaComparator();
        Collections.sort(this.listaVoo, new saidaComparator());
        
        // chegadaPrev - origem - cia. - voo - portao - chegadaEstimado - situacao        
        for(Voo obj : this.listaVoo){
            if(obj.consultarSaidas(textData.getText(), textCod.getText()) != null){
                String[] result = obj.consultarSaidas(textData.getText(), textCod.getText());            
                modelo.addRow(result);
            }
        }               
        tabelaSaidas.setModel(modelo);
        
        tabelaSaidas.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tabelaSaidas.getTableHeader().setOpaque(false);
        tabelaSaidas.getTableHeader().setBackground(Color.WHITE);
        tabelaSaidas.getTableHeader().setForeground(Color.GRAY);
        tabelaSaidas.setRowHeight(25);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelaChegadas;
    private javax.swing.JTable tabelaSaidas;
    private javax.swing.JTextField textCod;
    private javax.swing.JFormattedTextField textData;
    // End of variables declaration//GEN-END:variables
}
